site_title = "RoboArxiv"
limit_days = 30
cache_url = "https://qiaozhijian.github.io/RoboArxiv/cache.json"

[[sources]]
limit = 300
category = "cs.RO"
title = "Robotics"

[scripts]
highlight_title = "scripts/highlight_title.rhai"
highlight_author = "scripts/highlight_author.rhai"
highlight_conference = "scripts/highlight_conference.rhai"
